### ISSUE TITLE
Potential memory leak

### ISSUE THREAD

**Issue by riklempens** [oversight/wmiprobe#6]
Version 2.0.0 of the wmiprobe might have a memory leak.

## Logging

```
May 04 06:57:12 VAP00048.************** kernel: oom_reaper: reaped process 1702 (wmiprobe), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
May 04 06:57:12 VAP00048.************** kernel: Out of memory: Killed process 1702 (wmiprobe) total-vm:7251668kB, anon-rss:5573052kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:13140kB oom_score_adj:0
May 04 06:57:12 VAP00048.************** kernel: oom-kill: constraint=CONSTRAINT_NONE, nodemask=(null),cpuset=/,.mems_allowed=0,.global_oom,task_memcg=/docker/b61109a38363126afe5c5f43c7fa&daed0e41cefdc12b09b85df81d4ae2c0556,task=wmiprobe,pid=1702,uid=0
```

## Screenshot
<img width="1575" alt="CleanShot 2022-05-09 at 08 30 33@2x" src="https://user-images.githubusercontent.com/5619280/167352863-9a328f20-3db9-40cd-bea5-af1d28572160.png">

**Comment by joente** [comment]
Issue is resolved by using a queue to schedule checks in combination with small memory fixes in aiowmi. As the total run-time, due to time-outs could exceed the main scheduler, it was possible for checks to build tasks in memory which resulted in this leak. 

solved in https://github.com/oversight/wmiprobe/releases/tag/v2.0.2
